"use client";

import { FormEvent, useEffect, useState } from "react";
import { DashboardFrame } from "@/components/DashboardFrame";
import { ProtectedPage } from "@/components/ProtectedPage";
import { apiRequest } from "@/lib/api";

type AccountProfile={id:string;name:string;email:string;role:string;phone:string|null;address:string|null;is_active:boolean;created_at:string};
const nav=[{label:"Overview",href:"/customer",icon:"⌂"},{label:"My skin profile",href:"/customer#skin-profile",icon:"◌"},{label:"My routines",href:"/customer/routines",icon:"☼"},{label:"Wishlist",href:"/wishlist",icon:"♡"},{label:"My orders",href:"/customer/orders",icon:"▤"},{label:"Account settings",href:"/customer/settings",icon:"⚙"}];
export default function CustomerSettingsPage(){
 const [profile,setProfile]=useState<AccountProfile|null>(null);const [notice,setNotice]=useState("");const [error,setError]=useState("");const [busy,setBusy]=useState(false);
 useEffect(()=>{apiRequest<AccountProfile>("/api/users/profile").then(setProfile).catch((reason:Error)=>setError(reason.message));},[]);
 async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);setBusy(true);setError("");setNotice("");try{const updated=await apiRequest<AccountProfile>("/api/users/profile",{method:"PATCH",body:JSON.stringify({name:String(form.get("name")),phone:String(form.get("phone")||"")||null,address:String(form.get("address")||"")||null})});setProfile(updated);setNotice("Your account details are saved.");}catch(reason){setError(reason instanceof Error?reason.message:"Could not save account details.");}finally{setBusy(false);}}
 return <ProtectedPage role="customer"><DashboardFrame eyebrow="YOUR SPACE" title="Account settings" nav={nav}><div className="dashboard-welcome"><div><span className="eyebrow">YOUR ACCOUNT</span><h2>Keep your details up to date.</h2><p>Your address is used when placing an order. You can still choose a different address at checkout.</p></div></div>{notice&&<p className="inline-notice" role="status">{notice}</p>}{error&&<p className="form-error" role="alert">{error}</p>}<section className="dashboard-panel account-settings-panel"><span className="eyebrow">PERSONAL INFORMATION</span><h2>Profile details</h2>{profile?<form className="account-settings-form" onSubmit={save}><label>Full name<input name="name" required minLength={2} maxLength={120} defaultValue={profile.name}/></label><label>Email address<input value={profile.email} readOnly aria-describedby="email-help"/><small id="email-help">Email is used to sign in and cannot be changed here.</small></label><label>Phone number<input name="phone" type="tel" maxLength={32} defaultValue={profile.phone??""} placeholder="Add a contact number"/></label><label className="account-address-field">Default delivery address<textarea name="address" rows={4} maxLength={2000} defaultValue={profile.address??""} placeholder="Street, city, postal code, country"/></label><div className="account-settings-actions"><button className="button primary" type="submit" disabled={busy}>{busy?"Saving…":"Save changes"}</button><span>Account status: <b>{profile.is_active?"Active":"Inactive"}</b></span></div></form>:!error&&<p className="empty-state">Loading profile…</p>}</section></DashboardFrame></ProtectedPage>;
}
