"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { DashboardFrame } from "@/components/DashboardFrame";
import { ProtectedPage } from "@/components/ProtectedPage";
import { apiRequest } from "@/lib/api";

type Role="customer"|"seller"|"admin";
type UserRecord={id:string;name:string;email:string;role:Role;phone:string|null;is_active:boolean;created_at:string};
type UserResult={items:UserRecord[];total:number;page:number;page_size:number};
const nav=[{label:"Overview",href:"/admin",icon:"home"},{label:"Users",href:"/admin/users",icon:"user"},{label:"Sellers",href:"/admin/sellers",icon:"store"},{label:"Catalog",href:"/admin/catalog",icon:"catalog"},{label:"Product approvals",href:"/admin#approvals",icon:"check"},{label:"Reports",href:"/admin/reports",icon:"reports"},{label:"Content",href:"/admin/content",icon:"content"}];
export default function AdminUsersPage(){
 const [users,setUsers]=useState<UserRecord[]>([]);const [total,setTotal]=useState(0);const [query,setQuery]=useState("");const [search,setSearch]=useState("");const [sellerTarget,setSellerTarget]=useState<UserRecord|null>(null);const [storeName,setStoreName]=useState("");const [notice,setNotice]=useState("");const [error,setError]=useState("");const [busy,setBusy]=useState(false);
 const load=useCallback(()=>apiRequest<UserResult>(`/api/admin/users?page_size=100${search?`&q=${encodeURIComponent(search)}`:""}`).then((result)=>{setUsers(result.items);setTotal(result.total);}).catch((reason:Error)=>setError(reason.message)),[search]);
 useEffect(()=>{void load();},[load]);
 function submitSearch(event:FormEvent<HTMLFormElement>){event.preventDefault();setSearch(query.trim());}
 async function setRole(user:UserRecord,role:Role){if(role==="seller"&&user.role!=="seller"){setSellerTarget(user);setStoreName("");return;}await saveRole(user,role);}
 async function saveRole(user:UserRecord,role:Role,store_name?:string){setBusy(true);setError("");try{await apiRequest(`/api/admin/users/${user.id}/role`,{method:"PATCH",body:JSON.stringify({role,...(store_name?{store_name}:{})})});setSellerTarget(null);setStoreName("");setNotice(`${user.name} now has the ${role} role.`);await load();}catch(reason){setError(reason instanceof Error?reason.message:"Could not update this user's role.");}finally{setBusy(false);}}
 async function createSellerProfile(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!sellerTarget)return;await saveRole(sellerTarget,"seller",storeName);}
 async function toggleActive(user:UserRecord){setError("");try{await apiRequest(`/api/admin/users/${user.id}/status`,{method:"PATCH",body:JSON.stringify({is_active:!user.is_active})});setNotice(`${user.name}'s account is ${user.is_active?"inactive":"active"}.`);await load();}catch(reason){setError(reason instanceof Error?reason.message:"Could not update account status.");}}
 return <ProtectedPage role="admin"><DashboardFrame eyebrow="PLATFORM ADMIN" title="User management" nav={nav}><div className="dashboard-welcome"><div><span className="eyebrow">ACCOUNT ACCESS & ROLES</span><h2>Manage platform accounts.</h2><p>Search customer, seller, and admin accounts. Role changes are validated against seller records.</p></div></div>{notice&&<p className="inline-notice" role="status">{notice}</p>}{error&&<p className="form-error" role="alert">{error}</p>}<section className="dashboard-panel user-admin-panel"><form className="user-admin-search" role="search" onSubmit={submitSearch}><label htmlFor="user-search">Search users by name or email</label><input id="user-search" value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Name or email"/><button className="button primary" type="submit">Search</button><span>{total} account{total===1?"":"s"}</span></form><div className="user-admin-list">{users.map((user)=><article className="user-admin-row" key={user.id}><div className="user-admin-identity"><span className="user-admin-avatar" aria-hidden="true">{user.name.slice(0,1).toUpperCase()}</span><span><b>{user.name}</b><small>{user.email}</small><small>Joined {new Date(user.created_at).toLocaleDateString()}</small></span></div><label className="user-role-select">Role<select aria-label={`Role for ${user.name}`} value={user.role} onChange={(event)=>void setRole(user,event.target.value as Role)}><option value="customer">Customer</option><option value="seller">Seller</option><option value="admin">Admin</option></select></label><span className={`seller-account-state ${user.is_active?"active":"inactive"}`}>{user.is_active?"Active":"Inactive"}</span><button className="table-action" type="button" onClick={()=>void toggleActive(user)}>{user.is_active?"Deactivate":"Reactivate"}</button></article>)}{users.length===0&&!error&&<p className="empty-state">No accounts match this search.</p>}</div></section>{sellerTarget&&<div className="modal-backdrop"><section className="seller-role-modal" role="dialog" aria-modal="true" aria-labelledby="seller-role-heading"><button className="modal-close" type="button" aria-label="Close" onClick={()=>setSellerTarget(null)}>×</button><span className="eyebrow">SELLER PROFILE</span><h2 id="seller-role-heading">Assign seller access</h2><p>{sellerTarget.name} will receive a seller workspace. Add the public store name to create its seller profile.</p><form onSubmit={createSellerProfile}><label>Store name<input required minLength={2} maxLength={160} value={storeName} onChange={(event)=>setStoreName(event.target.value)} autoFocus/></label><div><button className="button primary" type="submit" disabled={busy}>{busy?"Saving…":"Assign seller role"}</button><button className="button outline" type="button" onClick={()=>setSellerTarget(null)}>Cancel</button></div></form></section></div>}</DashboardFrame></ProtectedPage>;
}
