"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { Header } from "@/components/Header";
import { apiRequest } from "@/lib/api";
type Article={id:string;title:string;description:string|null;category:string;source:string|null;url:string|null;created_at:string};
const categories=["All","Ingredient guide","Skincare basics","Routine guide","Product usage","Video"];
export default function LearnPage(){
 const [articles,setArticles]=useState<Article[]>([]);const [category,setCategory]=useState("All");const [query,setQuery]=useState("");const [error,setError]=useState("");
 useEffect(()=>{apiRequest<Article[]>("/api/content").then(setArticles).catch((reason:Error)=>setError(reason.message));},[]);
 const visible=useMemo(()=>articles.filter((article)=>{const categoryMatches=category==="All"||article.category.toLowerCase()===category.toLowerCase();const term=query.trim().toLowerCase();return categoryMatches&&(!term||`${article.title} ${article.description??""} ${article.category}`.toLowerCase().includes(term));}),[articles,category,query]);
 return <><Header/><main className="learning-page"><div className="learning-hero"><span className="eyebrow">A LITTLE MORE KNOWLEDGE</span><h1>Skincare, made clearer.</h1><p>Gentle, practical guides to help you make sense of ingredients, routines, and product use.</p><label className="learning-search"><span className="sr-only">Search learning resources</span><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Search skincare guides…"/></label></div><div className="learn-toolbar"><div className="learn-categories" aria-label="Filter by category">{categories.map((item)=><button className={category===item?"filter-chip active":"filter-chip"} key={item} type="button" onClick={()=>setCategory(item)}>{item}</button>)}</div><Link className="text-link" href="/ingredients">Explore ingredient directory →</Link></div>{error&&<p className="form-error" role="alert">{error}</p>}<section className="learn-grid" aria-label="Educational resources">{visible.map((article,index)=><article className="learn-card" key={article.id}><div className={`learn-art learn-art-${index%5}`}><span aria-hidden="true">{["✿","☼","◌","✧","❋"][index%5]}</span><small>{article.category}</small></div><div className="learn-card-body"><span className="eyebrow">{article.source||"DERMASPHERE GUIDE"}</span><h2>{article.title}</h2><p>{article.description||"An educational resource for thoughtful skincare."}</p>{article.url?<a className="text-link" href={article.url} target="_blank" rel="noreferrer">Open resource ↗</a>:<span className="learning-unavailable">Resource details coming soon</span>}</div></article>)}</section>{visible.length===0&&!error&&<div className="shop-empty"><h2>No guides match this view</h2><p>Try another search or category. New resources will appear here when published.</p><button className="button outline" type="button" onClick={()=>{setCategory("All");setQuery("");}}>Show all resources</button></div>}</main></>;
}
