"use client";
import { useEffect, useState } from "react";
import { ProtectedPage } from "@/components/ProtectedPage";
import { DashboardFrame, StatCards } from "@/components/DashboardFrame";
import { apiRequest } from "@/lib/api";

const nav = [{label:"Overview",href:"/admin",icon:"home"},{label:"Users",href:"/admin/users",icon:"user"},{label:"Sellers",href:"/admin/sellers",icon:"store"},{label:"Catalog",href:"/admin/catalog",icon:"catalog"},{label:"Product approvals",href:"/admin#approvals",icon:"check"},{label:"Orders",href:"/admin#orders",icon:"orders"},{label:"Reports",href:"/admin/reports",icon:"reports"},{label:"Content",href:"/admin/content",icon:"content"}];
const money = (value: unknown) => "$" + Number(value).toFixed(2);

export default function AdminDashboard() {
 const [stats,setStats]=useState<any>(null),[pending,setPending]=useState<any[]>([]),[users,setUsers]=useState<any[]>([]),[orders,setOrders]=useState<any[]>([]),[reviews,setReviews]=useState<any[]>([]),[notice,setNotice]=useState("");
 async function load(){try{const[s,p,u,o,r]=await Promise.all([apiRequest<any>("/api/admin/reports/overview"),apiRequest<any[]>("/api/admin/products/pending"),apiRequest<any>("/api/admin/users?page_size=30"),apiRequest<any[]>("/api/admin/orders"),apiRequest<any[]>("/api/admin/reviews/reported")]);setStats(s);setPending(p);setUsers(u.items);setOrders(o);setReviews(r);}catch(e){setNotice(e instanceof Error?e.message:"Could not load platform data.");}}
 useEffect(()=>{void load();},[]);
 async function decide(product:any,action:"approve"|"reject"){try{await apiRequest("/api/admin/products/"+product.id+"/"+action,{method:"PATCH",body:JSON.stringify({comment:action==="approve"?"Approved after review":"Please revise and resubmit"})});setNotice(product.name+" review saved.");await load();}catch(e){setNotice(e instanceof Error?e.message:"Could not update approval.");}}
 async function setActive(user:any){try{await apiRequest("/api/admin/users/"+user.id+"/status",{method:"PATCH",body:JSON.stringify({is_active:!user.is_active})});await load();}catch(e){setNotice(e instanceof Error?e.message:"Could not update account.");}}
 async function resolve(id:string){try{await apiRequest("/api/admin/reviews/"+id+"/report",{method:"PATCH",body:JSON.stringify({is_reported:false})});await load();}catch(e){setNotice(e instanceof Error?e.message:"Could not resolve report.");}}
 async function deleteReported(id:string){if(!window.confirm("Permanently delete this reported review?"))return;try{await apiRequest("/api/admin/reviews/"+id,{method:"DELETE"});setNotice("Reported review deleted.");await load();}catch(e){setNotice(e instanceof Error?e.message:"Could not delete review.");}}
 return <ProtectedPage role="admin"><DashboardFrame eyebrow="PLATFORM ADMIN" title="Platform overview" nav={nav}><div className="dashboard-welcome"><div><span className="eyebrow">ADMINISTRATOR</span><h2>Good morning.</h2><p>Review the marketplace and keep things running smoothly.</p></div></div>{notice&&<p className="dashboard-notice">{notice}</p>}{stats&&<><StatCards items={[{label:"Total users",value:stats.total_users,icon:"♙"},{label:"Sellers",value:stats.total_sellers,icon:"♧"},{label:"Pending products",value:stats.pending_products,icon:"◷"},{label:"Orders",value:stats.total_orders,icon:"▤"},{label:"Sales",value:money(stats.sales_total),icon:"⌁"},{label:"New users / 30d",value:stats.new_registrations_30d,icon:"＋"}]}/><section className="dashboard-panel" id="approvals"><span className="eyebrow">REVIEW QUEUE · {pending.length}</span><h2>Product approvals</h2>{pending.length?pending.map(p=><div className="approval-row" key={p.id}><span className="approval-thumb">✿</span><span className="approval-info"><b>{p.name}</b><small>{p.brand} · {money(p.price)}</small></span><button className="button primary" onClick={()=>decide(p,"approve")}>Approve</button><button className="button outline" onClick={()=>decide(p,"reject")}>Reject</button></div>):<p className="empty-state">All submitted products are reviewed.</p>}</section><div className="dashboard-columns"><section className="dashboard-panel" id="users"><span className="eyebrow">ACCOUNT OVERSIGHT</span><h2>Users and sellers</h2>{users.slice(0,10).map(u=><div className="data-row" key={u.id}><span><b>{u.name}</b><small>{u.email} · {u.role}</small></span><button className="table-action" onClick={()=>setActive(u)}>{u.is_active?"Deactivate":"Reactivate"}</button></div>)}</section><section className="dashboard-panel"><span className="eyebrow">COMMUNITY SAFETY</span><h2>Reported reviews</h2>{reviews.length?reviews.map(r=><div className="data-row" key={r.id}><span><b>{r.product_name} · {r.rating}/5</b><small>{r.body||"No review text"}</small></span><div className="review-moderation-actions"><button className="table-action" onClick={()=>resolve(r.id)}>Dismiss report</button><button className="text-button" onClick={()=>deleteReported(r.id)}>Delete review</button></div></div>):<p className="empty-state">No review reports to review.</p>}</section></div><section className="dashboard-panel" id="orders"><span className="eyebrow">FULFILMENT</span><h2>Recent orders</h2>{orders.slice(0,8).map(o=><div className="data-row" key={o.id}><span><b>{o.customer_name}</b><small>{o.id.slice(0,8)} · {o.status}</small></span><b>{money(o.total_amount)}</b></div>)}</section><div className="dashboard-panel" id="reports"><span className="eyebrow">DATA-DRIVEN OVERSIGHT</span><h2>Reports and content</h2><a className="report-link" href="/admin/reports">View sales, inventory, and skin profile reports →</a></div></>}</DashboardFrame></ProtectedPage>;
}
