"use client";
import {useEffect,useState} from "react";
import {apiRequest} from "@/lib/api";

type Product={id:string;name:string;brand:string;description:string;price:number|string;image_url:string|null;average_rating:number;review_count:number;available_quantity:number};
const formatPrice=(value:unknown)=>"$"+Number(value).toFixed(2);
export function LiveProducts({limit=20,query=""}:{limit?:number;query?:string}){
 const[items,setItems]=useState<Product[]>([]);const[loading,setLoading]=useState(true);const[notice,setNotice]=useState("");
 useEffect(()=>{const params=new URLSearchParams({page_size:String(limit),in_stock:"true"});if(query)params.set("q",query);apiRequest<{items:Product[]}>("/api/products?"+params.toString()).then(r=>setItems(r.items)).catch(e=>setNotice(e.message)).finally(()=>setLoading(false));},[limit,query]);
 async function add(item:Product,action:"cart"|"wishlist"){try{if(action==="cart")await apiRequest("/api/cart/items",{method:"POST",body:JSON.stringify({product_id:item.id,quantity:1})});else await apiRequest("/api/wishlist/"+item.id,{method:"POST"});setNotice(action==="cart"?"Added to your bag.":"Saved to your wishlist.");}catch(e){setNotice(e instanceof Error?e.message:"Please sign in to save this item.");}}
 return <>{notice&&<p className="dashboard-notice" role="status">{notice}</p>}{loading?<p className="empty-state">Finding products for your routine…</p>:items.length?<div className="product-grid">{items.map(item=><article className="product-card" key={item.id}><a className="product-image live-product-image" href={"/products/"+item.id}>{item.image_url?<img src={item.image_url} alt={item.name}/>:<div className="product-illustration dropper" aria-hidden="true"><span className="product-cap-shape"/><span className="product-glass"><span className="pack-logo">{item.brand}</span><span className="pack-name">{item.name}</span></span></div>}<span className="stock-label">{item.available_quantity} in stock</span></a><div className="product-details"><span className="product-brand">{item.brand}</span><h3><a href={"/products/"+item.id}>{item.name}</a></h3><div className="rating" aria-label={item.average_rating+" out of 5 stars"}>★★★★★ <span>{item.average_rating?item.average_rating.toFixed(1):"New"} <small>({item.review_count})</small></span></div><div className="product-buy"><b>{formatPrice(item.price)}</b><span className="stock">● Available</span></div><div className="live-product-actions"><button className="button primary add-button" onClick={()=>add(item,"cart")}>Add to bag</button><button className="live-wishlist" onClick={()=>add(item,"wishlist")} aria-label={"Save "+item.name+" to wishlist"}>♡</button></div></div></article>)}</div>:<p className="empty-state">No approved in-stock products are available yet.</p>}</>;
}
