"use client";
import {FormEvent,useEffect,useState} from "react";
import {Header} from "@/components/Header";
import {Footer} from "@/components/Footer";
import {ProductGrid,CatalogProduct} from "@/components/ProductGrid";
import {apiRequest} from "@/lib/api";

type Option={id:string;name:string};
export default function ProductsPage(){
 const[items,setItems]=useState<CatalogProduct[]>([]);const[categories,setCategories]=useState<Option[]>([]);const[types,setTypes]=useState<Option[]>([]);const[concerns,setConcerns]=useState<Option[]>([]);const[ingredients,setIngredients]=useState<Option[]>([]);const[total,setTotal]=useState(0);const[page,setPage]=useState(1);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[query,setQuery]=useState("");const[filters,setFilters]=useState("");
 useEffect(()=>{const params=new URLSearchParams(window.location.search);setQuery(params.get("q")||"");setFilters(params.toString());Promise.all([apiRequest<Option[]>("/api/categories"),apiRequest<Option[]>("/api/skin-types"),apiRequest<Option[]>("/api/skin-concerns"),apiRequest<Option[]>("/api/ingredients")]).then(([a,b,c,d])=>{setCategories(a);setTypes(b);setConcerns(c);setIngredients(d);}).catch(()=>{});},[]);
 useEffect(()=>{setLoading(true);apiRequest<{items:CatalogProduct[];total:number}>("/api/products?"+filters+(filters?"&":"")+"page="+page+"&page_size=20").then(r=>{setItems(r.items);setTotal(r.total);setError("");}).catch(e=>setError(e.message)).finally(()=>setLoading(false));},[filters,page]);
 function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);const params=new URLSearchParams();for(const key of ["q","category_id","skin_type_id","skin_concern_id","ingredient_id","min_price","max_price","min_rating"]){const value=String(form.get(key)||"").trim();if(value)params.set(key,value);}if(form.get("in_stock")==="yes")params.set("in_stock","true");setPage(1);setFilters(params.toString());const url=params.toString()?"/products?"+params.toString():"/products";window.history.replaceState(null,"",url);}
 return <><Header/><main className="catalog-page"><div className="catalog-intro"><span className="eyebrow">THE DERMASPHERE EDIT</span><h1>Find your next favourite.</h1><p>Explore approved skincare, clear ingredients, and the right details for your routine.</p></div><form className="catalog-filters" onSubmit={submit}><label>Search<input name="q" defaultValue={query} placeholder="Product, brand, or ingredient"/></label><label>Category<select name="category_id" defaultValue=""><option value="">All categories</option>{categories.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Skin type<select name="skin_type_id" defaultValue=""><option value="">Any skin type</option>{types.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Concern<select name="skin_concern_id" defaultValue=""><option value="">Any concern</option>{concerns.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Ingredient<select name="ingredient_id" defaultValue=""><option value="">Any ingredient</option>{ingredients.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Price from<input name="min_price" type="number" min="0" step="0.01" placeholder="0"/></label><label>Price to<input name="max_price" type="number" min="0" step="0.01" placeholder="Any"/></label><label>Rating<select name="min_rating" defaultValue=""><option value="">Any rating</option><option value="4">4+ stars</option><option value="4.5">4.5+ stars</option></select></label><label className="stock-filter"><input type="checkbox" name="in_stock" value="yes"/> In stock only</label><button className="button primary">Apply filters</button></form><div className="catalog-heading"><h2>{query?"Results for “"+query+"”":"Shop all skincare"}</h2><span>{total} approved products</span></div>{error&&<p className="form-error" role="alert">{error}</p>}{loading?<p className="empty-state">Loading products…</p>:items.length?<ProductGrid items={items}/>:<p className="empty-state">No approved products match these filters. Try a wider search.</p>}<div className="pagination"><button className="button outline" disabled={page===1} onClick={()=>setPage(page-1)}>← Previous</button><span>Page {page}</span><button className="button outline" disabled={page*20>=total} onClick={()=>setPage(page+1)}>Next →</button></div></main><Footer/></>;
}
