"use client";
import { useEffect, useState } from "react";
import { ProtectedPage } from "@/components/ProtectedPage";
import { DashboardFrame, StatCards } from "@/components/DashboardFrame";
import { apiRequest } from "@/lib/api";

const nav = [{label:"Overview",href:"/customer",icon:"âŒ‚"},{label:"My skin profile",href:"/customer#skin-profile",icon:"â—Œ"},{label:"My routines",href:"/customer/routines",icon:"â˜¼"},{label:"Wishlist",href:"/wishlist",icon:"â™¡"},{label:"My orders",href:"/customer#orders",icon:"â–¤"},{label:"AI history",href:"/customer#ai-history",icon:"âœ³"}];
type Profile = { skin_type: {id:string;name:string}|null; skin_concerns: {id:string;name:string}[]; budget_min:string|null; budget_max:string|null; preferences:string|null };
type RecordItem = {id:string;name:string;status?:string;created_at?:string;total_amount?:string;routine_type?:string;products?:unknown[];query?:string};
const money = (value: unknown) => "$" + Number(value).toFixed(2);

export default function CustomerDashboard() {
 const [profile,setProfile]=useState<Profile|null>(null),[orders,setOrders]=useState<RecordItem[]>([]),[routines,setRoutines]=useState<RecordItem[]>([]),[types,setTypes]=useState<{id:string;name:string}[]>([]),[concerns,setConcerns]=useState<{id:string;name:string}[]>([]),[history,setHistory]=useState<RecordItem[]>([]),[notice,setNotice]=useState("");
 useEffect(()=>{Promise.all([apiRequest<Profile>("/api/users/profile/skin"),apiRequest<RecordItem[]>("/api/orders"),apiRequest<RecordItem[]>("/api/routines"),apiRequest<{id:string;name:string}[]>("/api/skin-types"),apiRequest<{id:string;name:string}[]>("/api/skin-concerns"),apiRequest<RecordItem[]>("/api/ai/history")]).then(([p,o,r,t,c,h])=>{setProfile(p);setOrders(o);setRoutines(r);setTypes(t);setConcerns(c);setHistory(h);}).catch(e=>setNotice(e.message));},[]);
 async function save(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget);const payload={skin_type_id:String(f.get("skin_type_id")||"")||null,skin_concern_ids:f.getAll("concerns").map(String),budget_min:String(f.get("budget_min")||"")||null,budget_max:String(f.get("budget_max")||"")||null,preferences:String(f.get("preferences")||"")};try{setProfile(await apiRequest<Profile>("/api/users/profile/skin",{method:"PUT",body:JSON.stringify(payload)}));setNotice("Your skin profile is saved.");}catch(e){setNotice(e instanceof Error?e.message:"Could not save your profile.");}}
 return <ProtectedPage role="customer"><DashboardFrame eyebrow="YOUR SPACE" title="Your skin journey" nav={nav}><div className="dashboard-welcome"><div><span className="eyebrow">A GENTLE CHECK-IN</span><h2>Welcome back.</h2><p>Small, thoughtful steps add up. Hereâ€™s where you left off.</p></div><a className="button primary" href="/products">Explore products â†’</a></div>{notice&&<p className="dashboard-notice">{notice}</p>}<StatCards items={[{label:"Saved routines",value:routines.length,icon:"â˜¼"},{label:"Recent orders",value:orders.length,icon:"â–¤"},{label:"Skin concerns",value:profile?.skin_concerns.length??0,icon:"â—Œ"},{label:"AI conversations",value:history.length,icon:"âœ³"}]}/><div className="dashboard-columns"><section className="dashboard-panel" id="skin-profile"><span className="eyebrow">MADE PERSONAL</span><h2>Your skin profile</h2><form key={JSON.stringify(profile)} className="profile-form" onSubmit={save}><label>Skin type<select name="skin_type_id" defaultValue={profile?.skin_type?.id??""}><option value="">Choose skin type</option>{types.map(t=><option value={t.id} key={t.id}>{t.name}</option>)}</select></label><fieldset><legend>Skin concerns</legend><div className="checkbox-grid">{concerns.map(c=><label key={c.id}><input name="concerns" type="checkbox" value={c.id} defaultChecked={profile?.skin_concerns.some(x=>x.id===c.id)}/>{c.name}</label>)}</div></fieldset><div className="form-two"><label>Minimum budget<input type="number" min="0" step="0.01" name="budget_min" defaultValue={profile?.budget_min??""}/></label><label>Maximum budget<input type="number" min="0" step="0.01" name="budget_max" defaultValue={profile?.budget_max??""}/></label></div><label>Preferences<textarea name="preferences" rows={3} defaultValue={profile?.preferences??""}/></label><button className="button primary">Save my profile</button></form></section><section className="dashboard-panel" id="orders"><span className="eyebrow">AT YOUR DOORSTEP</span><h2>Recent orders</h2>{orders.length?orders.slice(0,6).map(o=><div className="data-row" key={o.id}><span><b>Order {o.id.slice(0,8)}</b><small>{o.status}</small></span><b>{money(o.total_amount)}</b></div>):<p className="empty-state">Your order history will appear here.</p>}</section></div><div className="dashboard-columns"><section className="dashboard-panel"><span className="eyebrow">YOUR RITUALS</span><h2>My routines</h2>{routines.slice(0,4).map(r=><div className="data-row" key={r.id}><span><b>{r.name}</b><small>{r.routine_type} Â· {r.products?.length??0} products</small></span></div>)}<a className="button outline" href="/customer/routines">Manage routines</a></section><section className="dashboard-panel" id="ai-history"><span className="eyebrow">PERSONAL GUIDANCE</span><h2>AI conversations</h2>{history.slice(0,4).map(h=><div className="data-row" key={h.id}><b>{h.query}</b></div>)}<a className="text-link" href="/assistant">Ask a question â†’</a></section></div></DashboardFrame></ProtectedPage>;
}

