"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { DashboardFrame } from "@/components/DashboardFrame";
import { ProtectedPage } from "@/components/ProtectedPage";
import { apiRequest } from "@/lib/api";

type Seller={id:string;user_id:string;name:string;email:string;store_name:string;description:string|null;verification_status:string;is_active:boolean};
const navigation=[{label:"Overview",href:"/admin",icon:"⌂"},{label:"Users",href:"/admin#users",icon:"♙"},{label:"Sellers",href:"/admin/sellers",icon:"♧"},{label:"Product approvals",href:"/admin#approvals",icon:"✓"},{label:"Reports",href:"/admin/reports",icon:"▥"},{label:"Content",href:"/admin/content",icon:"▧"}];
export default function AdminSellersPage(){
 const [sellers,setSellers]=useState<Seller[]>([]);const [query,setQuery]=useState("");const [search,setSearch]=useState("");const [notice,setNotice]=useState("");const [error,setError]=useState("");
 const load=useCallback(()=>apiRequest<Seller[]>(`/api/admin/sellers${search?`?q=${encodeURIComponent(search)}`:""}`).then(setSellers).catch((reason:Error)=>setError(reason.message)),[search]);
 useEffect(()=>{void load();},[load]);
 function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setSearch(query.trim());}
 async function setVerification(seller:Seller,value:string){try{await apiRequest(`/api/admin/sellers/${seller.id}/verification`,{method:"PATCH",body:JSON.stringify({verification_status:value})});setNotice(`${seller.store_name} verification updated.`);await load();}catch(reason){setError(reason instanceof Error?reason.message:"Could not update verification.");}}
 async function toggleActive(seller:Seller){try{await apiRequest(`/api/admin/users/${seller.user_id}/status`,{method:"PATCH",body:JSON.stringify({is_active:!seller.is_active})});setNotice(`${seller.store_name} account ${seller.is_active?"deactivated":"reactivated"}.`);await load();}catch(reason){setError(reason instanceof Error?reason.message:"Could not update seller account.");}}
 return <ProtectedPage role="admin"><DashboardFrame eyebrow="PLATFORM ADMIN" title="Seller management" nav={navigation}><div className="dashboard-welcome"><div><span className="eyebrow">SELLER OVERSIGHT</span><h2>Review seller accounts.</h2><p>Search stores, check verification state, and control account access.</p></div></div>{notice&&<p className="inline-notice" role="status">{notice}</p>}{error&&<p className="form-error" role="alert">{error}</p>}<section className="dashboard-panel seller-admin-panel"><form className="seller-admin-search" role="search" onSubmit={submit}><label htmlFor="seller-query">Search sellers and stores</label><input id="seller-query" value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Store, seller name, or email"/><button className="button primary" type="submit">Search</button></form><div className="seller-admin-list">{sellers.map((seller)=><article className="seller-admin-row" key={seller.id}><div className="seller-admin-identity"><span className="seller-admin-avatar" aria-hidden="true">♧</span><div><h2>{seller.store_name}</h2><p>{seller.name} · {seller.email}</p>{seller.description&&<small>{seller.description}</small>}</div></div><label className="verification-select">Verification<select value={seller.verification_status} onChange={(event)=>void setVerification(seller,event.target.value)}><option value="pending">Pending</option><option value="verified">Verified</option><option value="rejected">Rejected</option></select></label><span className={`seller-account-state ${seller.is_active?"active":"inactive"}`}>{seller.is_active?"Active account":"Inactive account"}</span><button className="table-action" type="button" onClick={()=>void toggleActive(seller)}>{seller.is_active?"Deactivate":"Reactivate"}</button></article>)}{sellers.length===0&&!error&&<p className="empty-state">No seller accounts match this search.</p>}</div></section></DashboardFrame></ProtectedPage>;
}
